### ISSUE TITLE
Add ending semicolon to improve compatibility

### ISSUE THREAD

**Issue by SeaHOH** [martok/js-darktree#1]
https://github.com/martok/js-darktree/blob/ad15e611e89c4002ac655f05f86d25a5744f29b1/src/darktree.js#L1071

**Comment by martok** [comment]
Compatibility with what? Pale Moon accepts it so Spidermonkey is OK, Terser accepts it so V8 is OK.

That's EOF, not even a linebreak where semicolon insertion could go wrong?

**Comment by SeaHOH** [comment]
Someone maybe direct write the whole content to HTML output as is, if a bracket pair follow up it, then cause error.
